artego/account/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import *
import information.views

app_name = "account"
urlpatterns = [
    path('login/', LoginView.as_view(template_name ='account/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name ='account/logout.html'), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('register/done/', UserCreateDoneTV.as_view(), name='register_done'),
    path('', information.views.main, name="main"),
]

artego/artego/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import information.views
import information.forms
# import account.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', information.views.main, name="main"),
    path('event/', information.views.event, name="event"),
    path('calendar/', information.views.calendar, name="calendar"),
    path('info/', information.views.info, name="info"),
    path('info/<int:blog_id>', information.views.detail, name="detail"),
    path('info/comment/<int:blog_id>', information.views.add_comment, name="add_comment"),
    path('search/', information.views.search, name="search"),
    path('account/', include('account.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

artego/information/urls.py
from django.contrib import admin
from django.urls import path, include
import information.views
import information.forms
# import account.views

urlpatterns = [
    path('search/', information.views.SearchFormView.as_view(), name='search'),
]

artego/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import artegoapp.views
import accounts.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', artegoapp.views.home, name = 'home'),
    path('artegoapp/', include('artegoapp.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, documents_root = settings.MEDIA_ROOT)

artego/account/models.py
from django.db import models

# Create your models here.

artego/information/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Information(models.Model):
    WISH=(
        ('V', 'visited'),
        ('W', 'wish'),
        ('N', 'not yet'),
    )
    title=models.CharField(max_length=200)
    image=models.ImageField(upload_to='images/', default="")
    info_data=models.TextField()
    wish=models.CharField(max_length=1, choices=WISH, default='N')
    
    def __str__(self):
        return self.title

class Comment(models.Model):
    post=models.ForeignKey(Information, related_name='comments', on_delete=models.CASCADE)
    author_name=models.CharField(max_length=20)
    comment_text=models.TextField()
    time=models.DateTimeField(default=timezone.now)

    def approve(self):
        self.save()
    
    def __str__(self):
        return self.comment_text

artego/information/forms.py
from django import forms
from .models import Comment


class SearchForm(forms.Form): 
    word = forms.CharField(label='Search Word')

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=('author_name', 'comment_text')

artego/account/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.views.generic.base import TemplateView
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy


class UserCreateView(CreateView):
    template_name = 'account/signup.html'
    form_class=UserCreationForm
    success_url=reverse_lazy('account:register_done')

class UserCreateDoneTV(TemplateView):
    template_name='account/register_done.html'

def main(request):
    return render(request, 'information/main.html')

artego/information/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Information
from django.contrib import messages
from django.db.models import Q
from .forms import CommentForm
from .forms import SearchForm
from django.views.generic.edit import FormView

# Create your views here.

def main(request):
    return render(request, 'main.html')

def info(request):
    informations=Information.objects
    return render(request, 'information.html', {'informations':informations})

def event(request):
    return render(request, 'event.html')

def calendar(request):
    return render(request, 'mycalendar.html')

def search(request):
    information=Information.objects.all()
    query=None

    if 'q' in request.GET:
        query=request.GET.get('q')
        if query:
            information = information.filter(title__icontains=query)
    return render(request, 'search.html', {'information' : information, 'query' : query})



def detail(request, blog_id):
    blog_object=get_object_or_404(Information, pk=blog_id)
    return render(request, 'detail.html', {'information':blog_object})

def add_comment(request, blog_id):
    blog=get_object_or_404(Information, pk=blog_id)
    
    if request.method == "POST":
        form=CommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.post=blog
            comment.save()
            return redirect('detail', blog_id)
    else:
        form=CommentForm()
        return render(request, 'review.html', {'form':form})

artego/information/templates/detail.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>ArtEgo</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <style>
    body{background-color: #DAD9D9;color: #365264;font-family: Arial;}
    header{text-align:center;font-size:50px;font-family:Arial, bold;padding:20px;}
    nav{padding:5px;overflow:hidden;text-align:right;}
    nav a{font-size:15px;display:block;color:#365264;text-decoration:none;}
    nav li{list-style:none;display:inline-block;padding:5px;}
    h2{font-family: Arial; font-size: 36px;}
    .wrapper{width: 1000px;margin: 20px auto;text-align: left;border:none;}

    #review-container:: after{content: "";clear: both;display: table;}
    .column{float:left; width:45%; height: 400px;margin: 10px; font-size: 20px;}
    .column img{float: right; height: 100%;}

    #info{padding: 10px;}
    #ttl{font-weight:bold;font-size: 24px;}
  </style>
</head>
<body>
  <div class = "wrapper" id = "reviewPage">
    <!--fixed UI until **---------------------------------------------->
    <section id = "menu-container">
        <nav>
          <ul>
            <li><a href="{%url 'info' %}"><i class="fa fa-fw fa-home"></i>HOME</a></li>
            <li><a href="{% url 'event' %}"><i class="fa fa-fw fa-star"></i>EVENT</a></li>
            <li><a href="{% url 'calendar' %}"><i class="fa fa-fw fa-calendar"></i>MY CALENDAR</a></li>
            <li><a href="{% url 'account:logout' %}"><i class="fa fa-fw fa-user"></i>LOG OUT</a></li>
          </ul>
        </nav>
        <!--Logo-->
        <header>ArtEgo</header>
      </section>
      <!-- ** -------------------------------------------------------->
      <!--title goes here-->
      <section id = "review-container">
        <div class = "column">
            <img src ="{{information.image.url}}" height=400 weight=600>
        </div>
        <div class = "column">
        <!--information on the exhibition-->
          <h1>information</h1>

<div>
    <h1>{{information.title}}</h1>
    <p>{{information.info_data}}</p>
    <p>{{information.wish}}</p>
</div>

<div>
    {% for comment in information.comments.all %}
        <h3>{{comment.author_name}}</h3>
        <p>{{comment.time}}</p>
        <p>{{comment.comment_text}}</p>
    {% empty %}
    <p>No comments here yet</p>
    {% endfor %}

    <br>
    <a href="{% url 'add_comment' information.id %}"><h2> new comment</h2></a>

</div>
        </div>
      </section>
  </div>
</body>
</html>

artego/information/templates/information.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ArtEgo</title>
  <style>
    body {
      background-color: #DAD9D9;
      color: #365264;
      font-family: Arial;
    }

    header {
      text-align: center;
      font-size: 50px;
      font-family: Arial, bold;
      padding: 20px;
    }

    nav {
      padding: 5px;
      overflow: hidden;
      text-align: right;
    }

    nav a {
      font-size: 15px;
      display: block;
      color: #365264;
      text-decoration: none;
    }

    nav li {
      list-style: none;
      display: inline-block;
      padding: 5px;
    }

    .wrapper {
      width: 1000px;
      margin: 20px auto;
      text-align: left;
      border: none;
    }

    .button {
      color: #365264;
      background-color: #DAD9D9;
      border: 0;
      outline: 0;
      cursor: pointer;
    }

    /*intro-container*/
    #enter-container {
      position: relative;
      margin: 10px;
      text-align: center;
    }

    #frontPage {
      text-align: center;
    }

    #intro-container {
      position: relative;
      margin-left: 20%;
      margin-right: 20%;
    }

    /*poster*/
    .poster0 {
      position: relative;
      width: 100%;
    }

    .image0 {
      position: relative;
      top: 0;
      left: 0;
      max-width: 100%;
    }

    .overlay0 {
      position: absolute;
      top: 0;
      bottom: 0;
      left: 0;
      right: 0;
      height: 100%;
      width: 100%;
      opacity: 0;
      transition: .5s ease;
      background-color: rgba(194, 203, 208, 0.5)
    }

    .poster0:hover .overlay0 {
      opacity: 1;
    }

    .text {
      color: white;
      font-size: 30px;
      position: absolute;
      top: 50%;
      left: 50%;
      text-decoration: none;
      -webkit-transform: translate(-50%, -50%);
      -ms-transform: translate(-50%, -50%);
    }

    body {
      background-color: #DAD9D9;
      color: #365264;
      font-family: Arial;
    }

    header {
      text-align: center;
      font-size: 50px;
      font-family: Arial, bold;
      padding: 20px;
    }

    nav {
      padding: 5px;
      overflow: hidden;
      text-align: right;
    }

    nav a {
      font-size: 15px;
      display: block;
      color: #365264;
      text-decoration: none;
    }

    nav li {
      list-style: none;
      display: inline-block;
      padding: 5px;
    }

    h2 {
      font-family: Arial;
      font-size: 36px;
    }

    .wrapper {
      width: 1000px;
      margin: 20px auto;
      text-align: left;
      border: none;
    }

    /*search*/
    .button {
      color: #365264;
      background-color: #DAD9D9;
      border: 0;
      outline: 0;
      cursor: pointer;
    }

    #search-engine {
      text-align: center;
    }

    #search-engine input {
      font-family: Verdana;
      text-align: left;
      width: 40%;
      height: 25px;
      border: 2px solid #365264;
      outline: 0;
    }

    #search-engine button {
      font-size: 20px;
    }

    #region-search {
      text-align: right;
    }

    #region-search button {
      font-family: Verdana, bold;
      font-size: 15px;
      padding-bottom: 5px;
    }

    .map {
      display: none;
      position: fixed;
      z-index: 1;
      padding-top: 100px;
      left: 0;
      top: 0;
      width: 100%;
      height: 100%;
      overflow: auto;
      background-color: rgba(0, 0, 0, 0.4);
    }

    .map-container {
      background-color: #edf0f1;
      margin: auto;
      padding: 20px;
      border: 1px solid #888;
      width: 60%;
      height: 80%;
    }

    .close {
      color: #365264;
      float: right;
      font-size: 28px;
      font-weight: bold;
      padding: 10px;
    }

    .close:hover,
    .close:focus {
      color: #000;
      text-decoration: none;
      cursor: pointer;
    }

    /*poster-list*/
    #image1 {
      clip: rect(0px, 1000px, 400px, 0px);
    }

    #image2 {
      clip: rect(400px, 1000px, 800px, 0px);
    }

    #image3 {
      clip: rect(800px, 1000px, 1200px, 0px);
    }

    #overlay2 {
      top: 400px;
    }

    #overlay3 {
      top: 800px;
    }

    .poster {
      position: absolute;
      width: 1000px;
    }

    .image {
      position: absolute;
      width: 1000px;
    }

    .overlay {
      position: absolute;
      top: 0;
      bottom: 0;
      left: 0;
      right: 0;
      height: 400px;
      width: 1000px;
      opacity: 0;
      transition: .5s ease;
      background-color: rgba(194, 203, 208, 0.5)
    }

    .poster:hover .overlay {
      opacity: 1;
    }

    .text {
      color: white;
      font-size: 30px;
      position: absolute;
      top: 50%;
      left: 50%;
      text-decoration: none;
      -webkit-transform: translate(-50%, -50%);
      -ms-transform: translate(-50%, -50%);
      transform: translate(-50%, -50%);
      text-align: right;
    }

    #view-more-container {
      display: block;
      border: 1px solid;
    }

    .reposter {
      position: relative;
    }
    .reposter:hover .overlay {opacity: 1;}
    .posterimage {
      width: 1000px;
      height: 400px;
      clip: rect(0px, 1000px, 400px, 0px);
      vertical-align: middle;
    }

    .postertext {
      color: white;
      font-size: 30px;
      position: absolute;
      text-align: center;
      top: 50%;
      left: 50%;
      -webkit-transform: translate(-50%, -50%);
      -ms-transform: translate(-50%, -50%);
      transform: translate(-50%, -50%);
    }

    a:link {
      text-decoration: none
    }

    a:visited {
      color: black;
    }

    .table {
      border-collapse: collapse;
      border-spacing: 0
    }
  </style>
</head>

<body>
  <div class="wrapper" id="frontPage">
    <!--fixed UI until **---------------------------------------->
    <section id="logged-out-main-container">

      {%if user.is_authenticated %}


      <div class="wrapper" id="mainPage">
        <!--fixed UI until **---------------------------------------------->
        <section id="menu-container">
          <nav>
            <ul>
              <li><a href="{%url 'info' %}"><i class="fa fa-fw fa-home"></i>HOME</a></li>
              <li><a href="{% url 'event' %}"><i class="fa fa-fw fa-star"></i>EVENT</a></li>
              <li><a href="{% url 'calendar' %}"><i class="fa fa-fw fa-calendar"></i>MY CALENDAR</a></li>
              <li><a href="{% url 'account:logout' %}"><i class="fa fa-fw fa-user"></i>LOG OUT</a></li>
            </ul>
          </nav>
          <!--Logo-->
          <header>ArtEgo</header>
        </section>
        <!-- ** -------------------------------------------------------->

        <section id="logged-in-main-container">
          <div id="search-engine">
            <br><br>
            <div>
              <form method="GET" action="{% url 'search' %}">
                {% csrf_token %}
                <input type="search" name="q" value="{{q}}">
                <button type="submit">Search</button>
              </form>
            </div>


          </div>
          <div id="region-search">

            <!--onclick => map UI-->
            <button id="mapButton" class="button">BY REGION</button>
            <div id="showMap" class="map">
              <div class="map-container">
                <div class="close">&times;</div>
                <div id="googleMap" style="width:100%;height:400px;"></div>
              </div>
            </div>
          </div>
        </section>
        <!--list of posters of the exhibitions-->
        <table class="table">
          {% for information in informations.all %}
          <tr>

            <div class="reposter">
              <img class="posterimage" src="{{ information.image.url }}">
              <div class="overlay">
                <a class="postertext" href="{% url 'detail' information.id %}">{{information.title}}</a></h1>
              </div>

            </div>
          </tr>
          {% endfor %}
        </table>


        <!-- for more information -->
        <section id="view-more-container">
          <button id="more">VIEW MORE</button>
        </section>
      </div>


      <script>
        var modal = document.getElementById("showMap");
        var btn = document.getElementById("mapButton");
        var span = document.getElementsByClassName("close")[0];

        //map-container
        btn.onclick = function () {
          modal.style.display = "block";
        }
        span.onclick = function () {
          modal.style.display = "none";
        }
        window.onclick = function (event) {
          if (event.target == modal) {
            modal.style.display = "none";
          }
        }

        //google-map
        function myMap() {
          var mapProp = {
            center: new google.maps.LatLng(51.508742, -0.120850),
            zoom: 5,
          };
          var map = new google.maps.Map(document.getElementById("googleMap"), mapProp);
        }
        //add marker
        var marker = new google.maps.Marker({
          position: myCenter
        });
        marker.setMap(map);

        var infowindow = new google.maps.InfoWindow({
          content: ""
        });
        google.maps.event.addListener(marker, 'click', function () {
          infowindow.open(map, marker);
        });

      </script>
      <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY&callback=myMap"></script>

      {% else %}
      <section id="logged-out-main-container">
        <header>ArtEgo</header>
      </section>
      <!-- **----------------------------------------------->
      <!--intro page-->
      <h2>Exhibition of This Month</h2>
      <section id="intro-container">
        <div class="poster0">
          <!--poster-->
          <img
            src="http://kor.theasian.asia/wp-content/uploads/2020/11/200929_%EB%A7%88%ED%8B%B0%EC%8A%A4%ED%8F%AC%EC%8A%A4%ED%84%B0RGB-620x882.jpg"
            class="image0">
          <div class="overlay0">
            <a class="text" href="{% url 'info' %}">Best of 2020<br>10th Dec, 2020<br>Seoul</a>
          </div>
        </div>
      </section>
      <section id="enter-container">
        <a href="{% url 'account:login' %}"><button id="logIn" class="button" style="font-size: 20px;">LOG
            IN</button></a>
        <a href="{% url 'account:register' %}"><button id="join" class="button"
            style="font-size: 20px;">JOIN</button></a>
      </section>
  </div>
  {% endif %}
</body>

</html>

artego/information/templates/main.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ArtEgo</title>
  <style>
    body {
      background-color: #DAD9D9;
      color: #365264;
      font-family: Arial;
    }

    header {
      text-align: center;
      font-size: 50px;
      font-family: Arial, bold;
      padding: 20px;
    }

    nav {
      padding: 5px;
      overflow: hidden;
      text-align: right;
    }

    nav a {
      font-size: 15px;
      display: block;
      color: #365264;
      text-decoration: none;
    }

    nav li {
      list-style: none;
      display: inline-block;
      padding: 5px;
    }

    .wrapper {
      width: 1000px;
      margin: 20px auto;
      text-align: left;
      border: none;
    }

    .button {
      color: #365264;
      background-color: #DAD9D9;
      border: 0;
      outline: 0;
      cursor: pointer;
    }

    /*intro-container*/
    #enter-container {
      position: relative;
      margin: 10px;
      text-align: center;
    }

    #frontPage {
      text-align: center;
    }

    #intro-container {
      position: relative;
      margin-left: 20%;
      margin-right: 20%;
    }

    /*poster*/
    .poster0 {
      position: relative;
      width: 100%;
    }

    .image0 {
      position: relative;
      top: 0;
      left: 0;
      max-width: 100%;
    }

    .overlay0 {
      position: absolute;
      top: 0;
      bottom: 0;
      left: 0;
      right: 0;
      height: 100%;
      width: 100%;
      opacity: 0;
      transition: .5s ease;
      background-color: rgba(194, 203, 208, 0.5)
    }

    .poster0:hover .overlay0 {
      opacity: 1;
    }

    .text {
      color: white;
      font-size: 30px;
      position: absolute;
      top: 50%;
      left: 50%;
      text-decoration: none;
      -webkit-transform: translate(-50%, -50%);
      -ms-transform: translate(-50%, -50%);
    }

    body{background-color: #DAD9D9;color: #365264;font-family: Arial;}
    header{text-align:center;font-size:50px;font-family:Arial, bold;padding:20px;}
    nav{padding:5px;overflow:hidden;text-align:right;}
    nav a{font-size:15px;display:block;color:#365264;text-decoration:none;}
    nav li{list-style:none;display:inline-block;padding:5px;}
    h2{font-family: Arial; font-size: 36px;}
    .wrapper{width: 1000px;margin: 20px auto;text-align: left;border:none;}

    /*search*/
    .button{color: #365264;background-color:#DAD9D9;border:0;outline:0;cursor: pointer;}
    #search-engine{text-align:center;}
    #search-engine input{font-family: Verdana;text-align:left;width:40%;height: 25px;
      border: 2px solid #365264;outline:0;}
    #search-engine button{font-size:20px;}
    #region-search {text-align:right;}
    #region-search button{font-family:Verdana, bold;font-size:15px; padding-bottom:5px;}
    .map {display: none;position: fixed;z-index: 1;padding-top: 100px;left: 0;top: 0;
      width: 100%;height: 100%;overflow: auto;background-color: rgba(0,0,0,0.4);}
    .map-container {background-color: #edf0f1;margin: auto;padding: 20px;border: 1px solid #888;
      width: 60%; height: 80%;}
    .close {color: #365264;float: right;font-size: 28px;font-weight: bold;padding: 10px;}
    .close:hover,
    .close:focus {color: #000;text-decoration: none;cursor: pointer;}

    /*poster-list*/
    #image1{clip:rect(0px, 1000px, 400px, 0px);}
    #image2{clip:rect(400px, 1000px, 800px, 0px);}
    #image3{clip:rect(800px, 1000px, 1200px, 0px);}
    #overlay2 {top:400px;}
    #overlay3{top:800px;}
    .poster{position: absolute; width: 1000px;}
    .image{position:absolute;width:1000px;}
    .overlay {position: absolute; top: 0; bottom: 0; left: 0; right: 0;height: 400px; width: 1000px;
      opacity: 0; transition: .5s ease; background-color: rgba(194, 203, 208,0.5)}
    .poster:hover .overlay {opacity: 1;}
    .text {color: white;font-size: 30px;position: absolute;top: 50%;left: 50%;text-decoration: none;
      -webkit-transform: translate(-50%, -50%);-ms-transform: translate(-50%, -50%);
      transform: translate(-50%, -50%);text-align: right;}

      #view-more-container{display:block; border:1px solid;}
  </style>
</head>

<body>
  <div class="wrapper" id="frontPage">
    <!--fixed UI until **---------------------------------------->
    <section id="logged-out-main-container">

    {%if user.is_authenticated %}
    

    <div class="wrapper" id="mainPage">
      <!--fixed UI until **---------------------------------------------->
      <section id="menu-container">
        <nav>
          <ul>
            <li><a href="{%url 'info' %}"><i class="fa fa-fw fa-home"></i>HOME</a></li>
            <li><a href="{% url 'event' %}"><i class="fa fa-fw fa-star"></i>EVENT</a></li>
            <li><a href="{% url 'calendar' %}"><i class="fa fa-fw fa-calendar"></i>MY CALENDAR</a></li>
            <li><a href="{% url 'account:logout' %}"><i class="fa fa-fw fa-user"></i>LOG OUT</a></li>
          </ul>
        </nav>
        <!--Logo-->
        <header>ArtEgo</header>
      </section>
      <!-- ** -------------------------------------------------------->

      <section id="logged-in-main-container">
        <div id="search-engine">
          <br><br>
            <div>
              <form method="GET" action="{% url 'search' %}">
                  {% csrf_token %}
                  <input type="search" name="q" value="{{q}}">
                  <button type="submit">Search</button>
              </form>
        </div>
        
        </div>
        <div id="region-search">

          <!--onclick => map UI-->
          <button id="mapButton" class="button">BY REGION</button>
          <div id="showMap" class="map">
            <div class="map-container">
              <div class="close">&times;</div>
              <div id="googleMap" style="width:100%;height:400px;"></div>
            </div>
          </div>
        </div>
      </section>
      <!--list of posters of the exhibitions-->

      <section id="exhibition-list-container">

        <div id="poster1" class="poster">
          <img src="http://spacelifes.com/wp-content/uploads/2017/09/2.jpg" id="image1" class="image">
          <div id="overlay1" class="overlay">
            <a class="text" href="{% url 'info' %}">Best of 2020<br>10th Dec, 2020<br>Seoul</a>
          </div>
        </div>
        <div id="poster2" class="poster">
          <img src="http://58.234.158.21:8081/Upload/Image/20170217/00000000000000016304.jpg" id="image2" class="image">
          <div id="overlay2" class="overlay">
            <a class="text">Best of 2020<br>10th Dec, 2020<br>Seoul</a>
          </div>
        </div>
        <div id="poster3" class="poster">
          <img src="http://www.art114.kr/files/attach/images/1337/112/598/1cda2cc1b363963a6909cbed521df07d.jpg"
            id="image3" class="image">
          <div id="overlay3" class="overlay">
            <a class="text">Best of 2020<br>10th Dec, 2020<br>Seoul</a>
          </div>
        </div>
      </section>

      <!-- for more information -->
      <section id="view-more-container">
        <button id="more">VIEW MORE</button>
      </section>
    </div>
    <div>
        {% for information in informations.all %}
         <div>
            <h1><a href="{% url 'detail' information.id %}">{{information.title}}</a></h1>
            <!-- <h1>{{information.wish}}</h1> -->
        </div>
        {% endfor %}
    </div>

    <script>
      var modal = document.getElementById("showMap");
      var btn = document.getElementById("mapButton");
      var span = document.getElementsByClassName("close")[0];

      //map-container
      btn.onclick = function () {
        modal.style.display = "block";
      }
      span.onclick = function () {
        modal.style.display = "none";
      }
      window.onclick = function (event) {
        if (event.target == modal) {
          modal.style.display = "none";
        }
      }

      //google-map
      function myMap() {
        var mapProp = {
          center: new google.maps.LatLng(51.508742, -0.120850),
          zoom: 5,
        };
        var map = new google.maps.Map(document.getElementById("googleMap"), mapProp);
      }
      //add marker
      var marker = new google.maps.Marker({
        position: myCenter
      });
      marker.setMap(map);

      var infowindow = new google.maps.InfoWindow({
        content: ""
      });
      google.maps.event.addListener(marker, 'click', function () {
        infowindow.open(map, marker);
      });

    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY&callback=myMap"></script>

    {% else %}
    <section id = "logged-out-main-container">
      <header>ArtEgo</header>
    </section>
    <!-- **----------------------------------------------->
    <!--intro page-->
      <h2>Exhibition of This Month</h2>
    <section id="intro-container">
      <div class="poster0">
        <!--poster-->
        <img
          src="http://kor.theasian.asia/wp-content/uploads/2020/11/200929_%EB%A7%88%ED%8B%B0%EC%8A%A4%ED%8F%AC%EC%8A%A4%ED%84%B0RGB-620x882.jpg"
          class="image0">
        <div class="overlay0">
          <a class="text" href="{% url 'info' %}">Best of 2020<br>10th Dec, 2020<br>Seoul</a>
        </div>
      </div>
    </section>
    <section id="enter-container">
      <a href="{% url 'account:login' %}"><button id="logIn" class="button" style="font-size: 20px;">LOG IN</button></a>
      <a href="{% url 'account:register' %}"><button id="join" class="button" style="font-size: 20px;">JOIN</button></a>
    </section>
  </div>
  {% endif %}
</body>

</html>